spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/caro_db?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        time_zone: Asia/Seoul
    show-sql: true
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${APP_PORT:8080}

api:
  client:
    url: http://localhost:3000
  server:
    url: http://localhost:8080

jwt:
  secret: ${JWT_SECRET:abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

logging:
  level:
    root: DEBUG
